# Generated by Django 4.0 on 2022-11-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fram',
            field=models.CharField(choices=[('0', 'django'), ('1', 'flask'), ('3', 'featured')], max_length=50),
        ),
    ]
